const word_dict = {
    easy : [  "time",  "year",  "day",  "way",  "man",  "world",
        "life",  "hand",  "part",  "child",  "eye",  "woman",  "place",
        "work",  "week",  "case",  "point",  "government",  "company",  "number",
        "group",  "problem",  "fact",  "beauty",  "idea",  "money",  "month",
        "home",  "water",  "system",  "area",  "bed",  "study",
        "job",  "book",  "word",  "business",  "issue",  "side",
        "kind",  "head",  "house",  "service",  "friend",  "father",
        "power",  "hour",  "game",  "line",  "end",  "member",  "law",
        "car",  "city",  "community",  "name",  "president",  "team",
        "minute",  "idea",  "kid",  "body",  "information",  "back",
        "parent",  "face",  "others",  "level",  "office",  "door",  "health",
        "person",  "art",  "war",  "history",  "party",  "result",  "change",  "morning",
        "reason",  "research",  "girl",  "guy",  "food",  "moment",  "air",  "teacher",
        "force",  "education",  "foot",  "girlfriend",  "lawyer",  "plan",  "boy",  "movie"],

    medium : [
        "allegory",  "blunderbuss",  "chimera",  "doppelganger",  "ephemera",  "flotsam",
        "gargoyle",  "harridan",  "iconoclast",  "juxtaposition",  "knickknack",  "labyrinth",
        "neophyte",  "onomatopoeia",  "paradox",  "quintessence",  "rhetoric",  "surrealism",
        "triskaidekaphobia",  "ubiquity",  "vagary",  "whimsy",  "xenophobia",  "yield",
        "zeitgeist",  "abacus",  "balustrade",  "cacophony",  "dilapidation",  "ephemeris",
        "fissure",  "gadfly",  "haiku",  "imbroglio",  "jamboree",  "kangaroo",  "luminary",
        "malaise",  "nonchalance",  "obfuscation",  "panacea",  "quadrilateral",  "rancor",
        "stagnation",  "tangential",  "ubiquitous",  "veneration",  "whetstone",  "xylophone",
        "yesteryear",  "zephyr",  "anachronism",  "benignity",  "calamity",  "disparagement",
        "enigma",  "flamboyance",  "galvanization",  "hierarchy",  "impropriety",  "jocularity",
        "kerfuffle",  "loquacity",  "maelstrom",  "nostalgia",  "oblivion",  "paranoia",  "quintessential",
        "repercussion",  "synchronicity",  "truculence",  "ululation",  "vicissitude",  "wholesomeness",
        "xeriscape",  "yearning",  "zeitgeber",  "aberration",  "benevolence",  "camaraderie",  "dichotomy",
        "esoteric",  "facetious",  "garrulous",  "histrionic",  "impetuous",  "joviality",  "kindred",
        "laconic",  "metamorphosis",  "naivety",  "orthography",  "paraphernalia",  "quintet",  "reverie",
        "serendipity",  "trepidation",  "unrequited",  "vociferous",  "welter",  "xenial",  "yielding",
        "zeitgeisty", "misanthrope"],

    hard : [  "apothecary",  "chimera",  "diadem",  "ennui",  "farrago",
        "garrulity",  "harangue",  "idyll",  "juggernaut",  "kismet",  "labyrinth",
        "maelstrom",  "neophyte",  "obfuscation",  "panacea",  "quagmire",  "raconteur",
        "serendipity",  "threnody",  "ubiquity",  "vexation",  "whimsy",  "xenophobia",  "yesteryear",
        "zeitgeist",  "abnegation",  "brouhaha",  "cynosure",  "dilettante",  "effulgence",  "felicity",
        "gadfly",  "hokum",  "iconoclast",  "jocularity",  "kaleidoscope",  "lackadaisical",  "malfeasance",
        "nefarious",  "obloquy",  "paragon",  "quandary",  "recalcitrant",  "sardonic",  "tenebrous",
        "ululation",  "venerable",  "weltschmerz",  "xylophone",  "yammer",  "zealot",  "acumen",  "bonhomie",
        "cachet",  "desuetude",  "eclectic",  "fastidious",  "genteel",  "histrionic",  "inexorable",
        "jubilation",  "knell",  "lascivious",  "misanthrope",  "nonplussed",  "oscillation",  "panoply",
        "querulous",  "recondite",  "sanguine",  "trepidation",  "ubiquitous",  "vacillation",  "winsome",
        "xeriscape",  "yestertide",  "zephyr",  "aberration",  "bucolic",  "cerebral",  "doggerel",  "epiphany",
        "facetious",  "gourmand",  "hauteur",  "inimitable",  "juxtaposition",  "kudos",  "legerdemain",
        "magnanimous",  "nocturnal",  "onerous",  "pedantic",  "quotidian",  "recusant",  "sagacious",
        "truculent",  "umbrage",  "vainglorious",  "weltanschauung",  "xenial",  "yearning",  "zestful"],

 self_harm : [  "abnegator",  "chirurgeon",  "dreikanter",  "eirenicon",  "flaneur",
        "gabelle",  "hanuman",  "incondite",  "jentacular",  "ktenology",  "logodaedalus",  "mumpsimus",
        "nidorosity",  "opinicus",  "pyknic",  "quarrenden",  "rhathymia",  "sabaism",  "thymiaterion",
        "uxoricide",  "ventifact",  "wittol",  "xanthippe",  "yeuky",  "zoanthropy",  "ambivert",  "bawcock",
        "callipygian",  "deipnosophist",  "ergometer",  "fossarian",  "galeanthropy",  "hagiology",  "idioticon",
        "joculator",  "kumiss",  "locrian",  "metathesis",  "necropolis",  "octothorp",  "pamphagous",  "querken",
        "rhizogenic",  "selcouth",  "teratogenic",  "ulmaceous",  "variscite",  "whiggarchy",  "xenagogue",
        "yaffingale",  "zymoscope",  "anemochore",  "bolometer",  "cachinnation",  "dauw",  "eccedentesiast",
        "flews",  "grimoire",  "intonaco",  "jaborandi",  "kakistocracy",  "larmoyant",
        "morigeration",  "narthex",  "obnubilation",  "phyllorhine",  "quotha",  "risorgimento",  "sarbacane",
          "ululation",  "viverrid",  "wastrel",  "xylomancy",  "younker",  "zamindari",
        "aspergillum",  "benthos",  "callithump",  "deracinate",  "epithymetic",  "fipple",  "gorgonize",
        "hendiadys",  "isopsephy",  "jumbuck",  "kern",  "lycanthropy",  "myrmidon",  "nidor",  "ossifrage",
        "preantepenultimate",  "quidnunc",  "ramiform",  "subfusc",  "triskelion",  "ultrafiltration",
        "vexillum",  "witchetty",  "xenops",  "yonic",  "zymurgy"],
}

